# Generated by Django 5.1.2 on 2024-11-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_repository_slackwebhook_pullrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='github_url',
            field=models.URLField(),
        ),
    ]
