# Generated by Django 5.1.2 on 2024-11-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_repository_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='github_url',
            field=models.URLField(unique=True),
        ),
    ]
